const TOTAL_SHEET="Total";
function createTotalSheet(){
  const ss=SpreadsheetApp.getActiveSpreadsheet(),names=[FIT_SHEET,SERVICE_SHEET,HOOL_SHEET,BREAKFAST_SHEET];let total=ss.getSheetByName(TOTAL_SHEET);if(!total)total=ss.insertSheet(TOTAL_SHEET);
  const old={},oldData=total.getDataRange().getDisplayValues();for(let i=1;i<oldData.length;i++){const no=String(oldData[i][0]||"").trim();if(no)old[no]={status:oldData[i][11]||oldData[i][9]||"",date:oldData[i][12]||oldData[i][10]||""};}
  const people={};names.forEach(name=>{const sh=ss.getSheetByName(name);if(!sh)return;const d=sh.getDataRange().getValues();if(d.length<2)return;const tc=d[0].indexOf("Нийт");if(tc<0)return;for(let r=1;r<d.length;r++){if(String(d[r][0]).trim()==="Нийт"||(!d[r][0]&&!d[r][2]))continue;const k=String(d[r][0]).trim()||String(d[r][1])+String(d[r][2]);if(!people[k])people[k]={no:d[r][0],ovog:d[r][1],ner:d[r][2],job:d[r][3],fit:0,service:0,hool:0,breakfast:0};let sum=0;for(let c=4;c<tc;c++){if(!isDateInCurrentPeriod_(d[0][c]))continue;const n=Number(d[r][c]);if(Number.isFinite(n))sum+=n;}if(name===FIT_SHEET)people[k].fit+=sum;if(name===SERVICE_SHEET)people[k].service+=sum;if(name===HOOL_SHEET)people[k].hool+=sum;if(name===BREAKFAST_SHEET)people[k].breakfast+=sum;}});
  const out=[["№","Овог","Нэр","Албан тушаал","FitFood нийт","ServiceFood нийт","Hool нийт","Өглөөний цай нийт","Нийт хоол","Өглөөний цай үнэ","Нийт үнэ","Ажилтан зөвшөөрөл","Зөвшөөрсөн огноо"]];Object.keys(people).forEach(k=>{const p=people[k],count=p.fit+p.hool+p.breakfast,bp=p.breakfast*12000,price=((p.fit+p.hool)*15000)+p.service+bp,s=old[String(p.no).trim()]||{};out.push([p.no,p.ovog,p.ner,p.job,p.fit,p.service,p.hool,p.breakfast,count,bp,price,s.status||"",s.date||""]);});
  total.clear();total.getRange(1,1,out.length,out[0].length).setValues(out);styleHeader_(total,out[0].length);total.autoResizeColumns(1,out[0].length);return true;
}
function getMyTotal(user){createTotalSheet();const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(TOTAL_SHEET),d=sh.getDataRange().getDisplayValues(),no=String(user.no||"").trim();for(let i=1;i<d.length;i++)if(String(d[i][0]).trim()===no)return{success:true,data:{no:d[i][0],ovog:d[i][1],ner:d[i][2],job:d[i][3],fit:d[i][4],service:d[i][5],hool:d[i][6],breakfast:d[i][7],total:d[i][8],breakfastPrice:d[i][9],price:d[i][10],status:d[i][11]||"",approvedDate:d[i][12]||""}};return{success:false,message:"Таны нийт дүн олдсонгүй"};}
function userApproveTotal(user){createTotalSheet();const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(TOTAL_SHEET),d=sh.getDataRange().getDisplayValues(),no=String(user.no||"").trim();for(let i=1;i<d.length;i++)if(String(d[i][0]).trim()===no){sh.getRange(i+1,12).setValue("Зөвшөөрсөн");sh.getRange(i+1,13).setValue(new Date());writeLog_("TOTAL_APPROVED",user,"Нийт дүнгээ зөвшөөрсөн",TOTAL_SHEET,i+1,12);return{success:true,message:"Та нийт дүнгээ зөвшөөрлөө"};}return{success:false,message:"Таны мөр Total sheet дээр олдсонгүй"};}
